language: c
script: asdf plugin-test postgis https://github.com/smashedtoatoms/asdf-postgres.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
